version: '3'
services:
  server:
    build: server
    ports:
     - "5000:5000"
    env_file:
      - .env.local
    volumes:
      - ./server:/usr/src/app/
      - ./anonymized_html:/usr/src/app/html/
